name: Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Coding Style Checks
        run: docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.4 php-cs-fixer fix --dry-run

      - name: Run Syntax Checks
        run: |
          docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.1 parallel-lint src
          docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.2 parallel-lint src
          docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.3 parallel-lint src
          docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php7.4 parallel-lint src

      - name: Setup Services
        run: |
          docker-compose up -d
          docker ps -a
          docker run --rm -v "$(pwd)":/var/www -t phpswoole/swoole:latest-dev composer install -n

      - name: Run Unit Tests
        run: docker exec -t $(docker ps -qf "name=app") bash -c "./vendor/bin/phpunit"

      - name: Stop and Remove Docker Containers
        run: docker-compose down
