name: Unit Tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Services
        run: |
          docker-compose up -d
          docker ps -a
          docker run --rm -v "$(pwd)":/var/www -t phpswoole/swoole:latest-dev composer install -n

      - name: Run Unit Tests
        run: docker exec -t $(docker ps -qf "name=app") bash -c "./vendor/bin/phpunit"

      - name: Stop and Remove Docker Containers
        run: docker-compose down
